// Flat config per https://nextjs.org/docs/app/api-reference/config/eslint
// `next lint` was removed in Next.js 16 — lint via the ESLint CLI (`pnpm lint`).
import { defineConfig, globalIgnores } from "eslint/config";
// Next.js + React + React Hooks rules, with Core Web Vitals rules raised to errors.
import nextVitals from "eslint-config-next/core-web-vitals";
// typescript-eslint `recommended`, as shipped by Next.js.
import nextTs from "eslint-config-next/typescript";
import tseslint from "typescript-eslint";

export default defineConfig([
  ...nextVitals,
  ...nextTs,
  // Type-aware rules on top of the `recommended` set that `nextTs` provides.
  {
    files: ["**/*.ts", "**/*.tsx"],
    extends: [
      tseslint.configs.recommendedTypeChecked,
      tseslint.configs.stylisticTypeChecked,
    ],
    languageOptions: {
      parserOptions: {
        // Resolve each file's tsconfig automatically for type information.
        projectService: true,
      },
    },
    rules: {
      // Allow both Array<T> and T[] syntax
      "@typescript-eslint/array-type": "off",
      // Allow both interface and type for type definitions
      "@typescript-eslint/consistent-type-definitions": "off",
      // Enforce using type imports for better tree-shaking
      "@typescript-eslint/consistent-type-imports": [
        "warn",
        { prefer: "type-imports", fixStyle: "inline-type-imports" },
      ],
      // Warn about unused variables, but ignore parameters starting with underscore
      "@typescript-eslint/no-unused-vars": [
        "warn",
        { argsIgnorePattern: "^_" },
      ],
      // Allow async functions without await
      "@typescript-eslint/require-await": "off",
      // Prevent common Promise misuse patterns, but allow void returns in JSX attributes
      "@typescript-eslint/no-misused-promises": [
        "error",
        { checksVoidReturn: { attributes: false } },
      ],
    },
  },
  {
    // Report any unused eslint-disable comments
    linterOptions: {
      reportUnusedDisableDirectives: true,
    },
  },
  // Re-declare eslint-config-next's default ignores, plus this project's own.
  globalIgnores([
    // Defaults of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Prisma client, regenerated by the postinstall hook:
    "generated/**",
  ]),
]);
